version: '1.0'
stages:
 - prepare
 - test
 - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'codefreshdemo/cf-example-python-django'
    revision: master
    git: github
  test_the_code:
     title: Run unit tests
     stage: test
     image: python:3.6-slim
     commands:
       - pip install -r requirements.txt --cache-dir=/codefresh/volume/pip-cache 
       - python -m unittest composeexample.utils    
  build_my_image:
    title: Building Docker Image
    stage: build
    type: build
    image_name: my-django-image
    working_directory: ./
    tag: full
    dockerfile: Dockerfile